package com.qxk.springall.springbootmybatis.mapper;

import com.qxk.springall.springbootmybatis.model.CoffeeWithMyBatisGenerator;
import com.qxk.springall.springbootmybatis.model.CoffeeWithMyBatisGeneratorExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface CoffeeWithMyBatisGeneratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Aug 05 00:45:38 CST 2021
     */
    long countByExample(CoffeeWithMyBatisGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Aug 05 00:45:38 CST 2021
     */
    int deleteByExample(CoffeeWithMyBatisGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Aug 05 00:45:38 CST 2021
     */
    @Delete({
        "delete from T_COFFEE",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Aug 05 00:45:38 CST 2021
     */
    @Insert({
        "insert into T_COFFEE (NAME, PRICE, ",
        "CREATE_TIME, UPDATE_TIME)",
        "values (#{name,jdbcType=VARCHAR}, #{price,jdbcType=BIGINT,typeHandler=com.qxk.springall.springbootmybatis.handler.MoneyTypeHandler}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="CALL IDENTITY()", keyProperty="id", before=false, resultType=Long.class)
    int insert(CoffeeWithMyBatisGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Aug 05 00:45:38 CST 2021
     */
    int insertSelective(CoffeeWithMyBatisGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Aug 05 00:45:38 CST 2021
     */
    List<CoffeeWithMyBatisGenerator> selectByExampleWithRowbounds(CoffeeWithMyBatisGeneratorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Aug 05 00:45:38 CST 2021
     */
    List<CoffeeWithMyBatisGenerator> selectByExample(CoffeeWithMyBatisGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Aug 05 00:45:38 CST 2021
     */
    @Select({
        "select",
        "ID, NAME, PRICE, CREATE_TIME, UPDATE_TIME",
        "from T_COFFEE",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.qxk.springall.springbootmybatis.mapper.CoffeeWithMyBatisGeneratorMapper.BaseResultMap")
    CoffeeWithMyBatisGenerator selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Aug 05 00:45:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") CoffeeWithMyBatisGenerator record, @Param("example") CoffeeWithMyBatisGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Aug 05 00:45:38 CST 2021
     */
    int updateByExample(@Param("record") CoffeeWithMyBatisGenerator record, @Param("example") CoffeeWithMyBatisGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Aug 05 00:45:38 CST 2021
     */
    int updateByPrimaryKeySelective(CoffeeWithMyBatisGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Aug 05 00:45:38 CST 2021
     */
    @Update({
        "update T_COFFEE",
        "set NAME = #{name,jdbcType=VARCHAR},",
          "PRICE = #{price,jdbcType=BIGINT,typeHandler=com.qxk.springall.springbootmybatis.handler.MoneyTypeHandler},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(CoffeeWithMyBatisGenerator record);
}
