server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: ["*"] #开启全部端点相关代码
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true #提供了使用post请求来关闭Spring Boot应用的功能

info:
  app:
    encoding: UTF-8
    jdk: 1.8