server:
  port: 80

management:
  security:
    enabled: false #关掉安全认证。如果需要开启这个功能的话还需引入spring-boot-starter-security依赖。除了使用Spring Security来开启监控路径安全认证外，还可以使用Shiro对监控路径进行权限控制。
  port: 80 #监控的端口和应用一致
  context-path: /monitor #actuator的访问路径
endpoints:
  shutdown:
    enabled: true #提供了使用post请求来关闭Spring Boot应用的功能